name: smart_recycling
description: "A smart recycling uses IA for recycler"

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_gemini: ^2.0.5
  shared_preferences: ^2.2.3
  flutter_onboarding_slider: ^1.0.11
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  provider: ^6.1.2
  lottie: ^2.7.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/onboard/
    - assets/images/
    - assets/lottie/
    - assets/icons/app/
    - secrets.json
